Repository AY2122S1-CS2103-F10-1/tp, pull requests merged in 2021-11, with the labels that each got.

#171 Revert "Navigate command history"
  src/main/java/seedu/address/ui/CommandBox.java
Labels: priority.High, type.Task

#169 Fix various bugs in UG and rejection rate
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RejectionRateCommand.java
Labels: priority.High, severity.Medium

#172 DG updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/rejection-rates/ActivityDiagram.puml
  docs/diagrams/rejection-rates/InitialState.puml
  docs/diagrams/rejection-rates/Step2.puml
  docs/diagrams/rejection-rates/Step3.puml
  docs/images/rejection-rates/ActivityDiagram.png
  docs/images/rejection-rates/Initial-state.png
  docs/images/rejection-rates/Step2.png
  docs/images/rejection-rates/Step3.png
  src/main/java/seedu/address/logic/commands/EditApplicantCommand.java
Labels: priority.High, severity.Medium

#179 Change 'mark' command to be case-sensitive
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/MarkApplicantStatusCommand.java
  src/main/java/seedu/address/model/ApplicantBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/test/java/seedu/address/logic/commands/AddPositionCommandTest.java
Labels: type.Bug, priority.High

#187 Update Description constraint message
  src/main/java/seedu/address/model/position/Description.java
Labels: type.Bug, priority.High

#189 Add line wrapping to usage messages for better readability
  src/main/java/seedu/address/logic/commands/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/AddPositionCommand.java
  src/main/java/seedu/address/logic/commands/DeleteApplicantCommand.java
  src/main/java/seedu/address/logic/commands/DeletePositionCommand.java
  src/main/java/seedu/address/logic/commands/EditApplicantCommand.java
  src/main/java/seedu/address/logic/commands/EditPositionCommand.java
  src/main/java/seedu/address/logic/commands/FilterApplicantCommand.java
  src/main/java/seedu/address/logic/commands/FindApplicantCommand.java
  src/main/java/seedu/address/logic/commands/MarkApplicantStatusCommand.java
  src/main/java/seedu/address/logic/commands/RejectionRateCommand.java
  src/main/java/seedu/address/logic/commands/VisualizePositionCommand.java
  src/main/java/seedu/address/logic/parser/FilterApplicantCommandParser.java
Labels: type.Bug, priority.Medium

#181 Update 'filter-applicant' command error message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/descriptors/FilterApplicantDescriptor.java
  src/main/java/seedu/address/model/position/Title.java
Labels: type.Bug, priority.Medium

#185 Handling of position with no applicants for 'visualize' command
  src/main/java/seedu/address/logic/commands/MarkApplicantStatusCommand.java
  src/main/java/seedu/address/logic/commands/VisualizePositionCommand.java
  src/main/java/seedu/address/model/ApplicantBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/test/java/seedu/address/logic/commands/AddPositionCommandTest.java
Labels: type.Bug, priority.High

#186 Bug fixes for visualize command
  src/main/java/seedu/address/logic/parser/VisualizePositionCommandParser.java
  src/main/java/seedu/address/ui/PositionPieChart.java
Labels: type.Bug, priority.High

#112 Changed UI of MTR
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/Applicant.png
  src/main/resources/images/MrTechRecruiter.png
  src/main/resources/images/Position.png
  src/main/resources/view/ApplicantListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/testutil/ApplicantBuilder.java
Labels: priority.High

#194 Modify duplicate detection for Applicants and Positions
  src/main/java/seedu/address/logic/commands/AddApplicantCommand.java
  src/main/java/seedu/address/logic/commands/FilterApplicantCommand.java
  src/main/java/seedu/address/logic/commands/MarkApplicantStatusCommand.java
  src/main/java/seedu/address/logic/commands/RejectionRateCommand.java
  src/main/java/seedu/address/logic/commands/VisualizePositionCommand.java
  src/main/java/seedu/address/logic/descriptors/EditApplicantDescriptor.java
  src/main/java/seedu/address/logic/descriptors/FilterApplicantDescriptor.java
  src/main/java/seedu/address/logic/descriptors/FilterApplicantDescriptorVerifier.java
  src/main/java/seedu/address/logic/parser/AddApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/ApplicantParserUtil.java
  src/main/java/seedu/address/logic/parser/EditApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/FilterApplicantCommandParser.java
  src/main/java/seedu/address/logic/parser/MarkApplicantStatusCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RejectionRateCommandParser.java
  src/main/java/seedu/address/logic/parser/VisualizePositionCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PositionBook.java
  src/main/java/seedu/address/model/ReadOnlyPositionBook.java
  src/main/java/seedu/address/model/applicant/ApplicantMatchesFiltersPredicate.java
  src/main/java/seedu/address/model/applicant/Name.java
  src/main/java/seedu/address/model/position/Position.java
  src/main/java/seedu/address/model/position/Title.java
  src/main/java/seedu/address/model/position/UniquePositionList.java
  src/main/java/seedu/address/storage/applicant/JsonAdaptedApplicant.java
  src/test/java/seedu/address/logic/commands/AddPositionCommandTest.java
  src/test/java/seedu/address/model/applicant/ApplicantTest.java
  src/test/java/seedu/address/model/position/PositionTest.java
Labels: type.Bug, priority.High

#197 Added Appendix for effort in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Low

#200 DG updates for v1.4
  docs/DeveloperGuide.md
  docs/diagrams/ApplicantPositionClassDiagram.puml
  docs/diagrams/FilterApplicantSequenceDiagram0.puml
  docs/diagrams/FilterApplicantSequenceDiagram1.puml
  docs/diagrams/MarkApplicantActivityDiagram.puml
  docs/diagrams/VisualizeActivityDiagram.puml
  docs/diagrams/VisualizeSequenceDiagram.puml
  docs/images/ApplicantPositionClassDiagram.png
  docs/images/FilterApplicantSequenceDiagram0.png
  docs/images/FilterApplicantSequenceDiagram1.png
  docs/images/MarkApplicantActivityDiagram.png
  docs/images/VisualizeActivityDiagram.png
  docs/images/VisualizeSequenceDiagram.png
Labels: priority.High, type.Task

#210 Update PPP
  docs/team/lmaoboxhack.md
Labels: priority.High, type.Task

#208 Fix visual bugs in DG
  docs/DeveloperGuide.md
  docs/team/lmaoboxhack.md
Labels: type.Bug, priority.High

#225 Resize DG images
  docs/DeveloperGuide.md
  docs/diagrams/FilterApplicantSequenceDiagram0.puml
  docs/diagrams/FilterApplicantSequenceDiagram1.puml
  docs/images/FilterApplicantSequenceDiagram0.png
  docs/images/FilterApplicantSequenceDiagram1.png
  docs/team/lmaoboxhack.md
Labels: priority.High, type.Task

#226 Update Effort section for DG
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#227 Shorten PPP
  docs/team/lmaoboxhack.md
Labels: priority.High, type.Task
